base_url = "https://semanticdata.github.io/zola-tale/"
title = "Miguel Pimentel"
description = "I'm Miguel—hobby developer, music enjoyer, and public infrastructure enthusiast."

compile_sass = true
generate_feed = true
build_search_index = false
taxonomies = [
  { name = "tags", feed = true },
]

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-light"

[extra]
author = "Miguel Pimentel"
github = "https://github.com/semanticdata"
email = "contact@miguelpimentel.do"
timeformat = "%B %e, %Y" # e.g. June 14, 2021
katex = false
disqus = false
# disqus_id = ""
# google_analytics = ""

[[extra.menu]]
name = "Archive"
url = "/"

[[extra.menu]]
name = "Tags"
url = "tags"

[[extra.menu]]
name = "About"
url = "about"

[extra.footer]
start_year = "2023" # start year of the site
end_year = "2023" # end year of the site
info = "Powered by <a href=\"https://www.getzola.org\">Zola</a> and <a href=\"https://github.com/aaranxu/tale-zola\">Tale</a>."

[extra.expressions]
home = "Home" # The homepage's name
written_by = "Written by" # Like: Written by Aaran Xu
on = "on" # Like: on May 3, 2021
top = "Top" # Go to the top of the page in the post
tags = "Tags" # In the page of Tags
disqus_discussion = "Discussion and feedback"
p404 = "404: Page not found"
p404_info = "Oops! We can't seem to find the page you are looking for."
p404_back_home_start = "Let's"
p404_back_home_with_link = "head back home"
p404_back_home_end = "."
# pinned = "Pinned" # On the header of the post list

[extra.seo]
og_locale = "en_US"
# image = "tale.png"
# image_height = 0
# image_width = 0

# [extra.seo.twitter]
# site = "aaranxu"
# creator = "aaranxu"

# [extra.seo.facebook]
# admins = "ichunyun"
# publisher = "ichunyun"
# app_id = ""

# Webmaster verifications' tokens
# [extra.seo.webmaster]
# google = ""
# bing = ""
# alexa = ""
# yandex = ""
# baidu = ""