base_url = "https://d-j-harris.github.io/"
title = "Small Bytes"
description = "Occasional posts about what I've been learning and doing"

compile_sass = true
generate_feeds = true
feed_filenames = ["rss.xml", "atom.xml"]
minify_html = true
build_search_index = false
taxonomies = [{ name = "tags", feed = true }]

[markdown]
highlight_code = true
highlight_theme = "visual-studio-dark"
# More syntax highlighting themes: https://www.getzola.org/documentation/getting-started/configuration/#syntax-highlighting
smart_punctuation = true

[extra]
author = "Daniel Harris"
github = "https://github.com/D-J-Harris"
timeformat = "%B %e, %Y"  # e.g. June 14, 2021
katex_enable = true

[[extra.menu]]
name = "Home"
url = "/"

[[extra.menu]]
name = "Tags"
url = "tags"